### ISSUE TITLE
invalid link in requirements.txt

### ISSUE THREAD

**Issue by AbigaleD** [pixray/pixray#100]
fatal: unable to access 'https://github.com.cnpmjs.org/bfirsh/taming-transformers.git/': Could not resolve host: github.com.cnpmjs.org
  error: subprocess-exited-with-error

The link seems invalid in requirements.txt

**Comment by dribnet** [comment]
there's many things wrong with pixray, but that's not one of them 😂

the line in `requirements.txt` is 
```bash
git+https://github.com/bfirsh/taming-transformers.git@7a6e64ee
```

so not sure what is munging the domain there in your case.
