### ISSUE TITLE
AMD GPU Arch Linux

### ISSUE THREAD

**Issue by grhmhome** [pixray/pixray#12]
I was able to get Docker installed, but I have a AMD GPU (RX 580 OC). I get an error stating: docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ⅹ Docker is missing required device driver

What could I be missing? Thanks for your time.

**Comment by sgallag-insta** [comment]
Unfortunately Pixray won't work on an AMD GPU as it requires CUDA. You'll have to either run it in CPU mode or perhaps check out using a Colab notebook.
