### ISSUE TITLE
No module named 'diffusion'

### ISSUE THREAD

**Issue by Spilsed** [pixray/pixray#15]
I am using the command listed in the read me file to run Pixray using cog and docker but whenever I try to run the command I just end up getting the error that there is no module named 'diffusion'.

(I am running the latest version of Arch Linux if that matters)

```
Running 'python pixray.py --drawer=pixel --prompt=sunrise --output myfile.png' in Docker with the current directory mounted as a volume...
Traceback (most recent call last):
  File "pixray.py", line 69, in <module>
    from vdiff import VdiffDrawer
  File "/src/vdiff.py", line 38, in <module>
    from diffusion import get_model, get_models, sampling, utils
ModuleNotFoundError: No module named 'diffusion'
ⅹ exit status 1
```

**Comment by cassdeckard** [comment]
I'm also getting the same error in the Google Colab notebook: https://colab.research.google.com/github/pixray/pixray_notebooks/blob/master/pixray_minimal.ipynb

**Comment by Spilsed** [comment]
Solution for Arch Linux :
I am assuming this issue on Arch is because it doesn't have apt but in the cog.yaml when it runs it tries to execute the command `apt-get update` which I assume just stops the entire process without doing the next commands. These next commands include the command that downloads v-diffusion-pytorch causing this error to occur. My solution was just going into the cog.yaml and manually executing the commands though I think all you need to do is the `git clone https://github.com/pixray/v-diffusion-pytorch` command. (Remember I am using Arch)

If this does not work for you in the discord they were discussing this problem and seem to of fixed it though I cannot be sure.
The message just says "adding "import diffusion" after "import pixray" in settings code seems to fix it for me"
[Link to the discord message](https://ptb.discord.com/channels/887123022941679666/887181627493601292/930922607493152799)
