### ISSUE TITLE
SLIP - No module named 'tokenizer'

### ISSUE THREAD

**Issue by joaoachando** [pixray/pixray#17]
When trying to run the new v1.6 release it's not finding the tokenizer error.
The install procedure was the one on the documentation.

```
/content/pixray/slip.py in <module>
---> 80 from tokenizer import SimpleTokenizer

ModuleNotFoundError: No module named 'tokenizer'
```

**Comment by dribnet** [comment]
How are you running it, from the [updated notebooks](https://github.com/pixray/pixray_notebooks) or locally?

It might just need `clone --recursive` now that it has submoudles.

**Comment by dribnet** [comment]
This should now be fixed. Please reopen if this reappears.
