### ISSUE TITLE
Submodule is 404 - v-diffusion-pytorch @ 9ad961

### ISSUE THREAD

**Issue by Bug-Reaper** [pixray/pixray#18]
```
Resolving deltas: 100% (55/55), done.
Submodule path 'SLIP': checked out '22cc4058fe5747bfbd99c544a6476a0041d0d2de'
fatal: remote error: upload-pack: not our ref 9ad961d25670ecb1b59fb661e7a1e0b36dfc6470
fatal: Fetched in submodule path 'v-diffusion-pytorch', but it did not contain 9ad961d25670ecb1b59fb661e7a1e0b36dfc6470. Direct fetching of that commit failed.
fatal: 
```

Leads to:
```
  File "pixray/vdiff.py", line 34, in <module>
    from diffusion import get_model, get_models, sampling, utils
ModuleNotFoundError: No module named 'diffusion'
```

I see this is a new commit, sorry if I just caught you at some WIP moment.

**Comment by sgallag-insta** [comment]
As a temporary workaround, I've found some success with the following:

Local:
`git submodule update --init --force --remote`

Colab:
```
  %cd pixray
  !git checkout 2682864
  !git submodule update --init --recursive --force
  %cd ..
```

**Comment by sgallag-insta** [comment]
Looks like this may have been a transient github issue; this is working for me now

**Comment by sgallag-insta** [comment]
Update: this should now be working correctly

**Comment by dribnet** [comment]
Thanks and apologies for this snafu - I pushed up the new version without push up the submodule update. 🤭 I'll be more careful testing releases against the notebooks when updating the master branch.
