### ISSUE TITLE
add overlay_until

### ISSUE THREAD

**Issue by dribnet** [pixray/pixray#23]
idea from discord: be able to specify a point where the overlays are stopped - either as a percentage or as a raw iteration count

**Comment by sgallag-insta** [comment]
Is this something friendly for someone who knows unfamiliar with image processing? If it's not too hard I would be willing to take a stab at it

**Comment by dribnet** [comment]
Thanks - I think this is a very basic change to the logic of when to apply the overlay and adding a condition based on a new config variable to [this if statement](https://github.com/pixray/pixray/blob/217def174f2629f63b837a7d261ce6c472dcb905/pixray.py#L1401-L1402). It's a very low priority issue but just wanted to file it before I forgot...

**Comment by dribnet** [comment]
Fixed in #27 🎉
