### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by ggrantrowberry** [pixray/pixray#26]
I cloned the repo and ran the example run command. 

` cog run python pixray.py --drawer=pixel --prompt=sunrise --output sunrise.png`

After it built the docker container I got this error. 

```Running 'python pixray.py --drawer=pixel --prompt=sunrise --output sunrise.png' in Docker with the current directory mounted as a volume...
Traceback (most recent call last):
  File "pixray.py", line 32, in <module>
    from slip import get_clip_perceptor
  File "/src/slip.py", line 81, in <module>
    from tokenizer import SimpleTokenizer
ModuleNotFoundError: No module named 'tokenizer'
```

I imagine this shouldn't be too bad to fix. I'm assuming something is missing from the requirements.txt. However I added the package tokenizer to requirements.txt and it gave me the error

`ImportError: cannot import name 'SimpleTokenizer' from 'tokenizer'`

I did notice that the import was under this in slip.py line 76.

```
# TODO: this is very hacky, must fix this later (submodule dependency)
SLIP_PATH = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'SLIP')
# print("APPENDING PATH ", SLIP_PATH)
sys.path.append(SLIP_PATH)
import models
from tokenizer import SimpleTokenizer
import utils
```
Any thoughts on what do I need to do to get this to work? 

Thanks

**Comment by lazreg87** [comment]
If you cloned without the `--recursive` flag, run `git submodule update --init` to fetch the missing git submodules. Should work after that

**Comment by ggrantrowberry** [comment]
Cool! The `git submodule update --init` didn't work for me, but deleting it and cloning it again with the `--recursive` flag worked.
