### ISSUE TITLE
Cannot select size in command line

### ISSUE THREAD

**Issue by matteovaccari** [pixray/pixray#42]
Hello and thank you for this awesome library
Here's my issue : 

`python3 pixray.py --prompt="summer" --iterations=250 --outdir="OUTPUT" --size=1000,700
`
No matter which syntax I try, i cannot manage to change the size 
I've tryied : 
-s = x y
--size x y 
--size = x, y
--size=[x,y]
--size="x,y"
--size=["x","y"]
--size=[x,y]
...
Does anyone managed to set this parameter correctly ?
Thank you all!

**Comment by matteovaccari** [comment]
EDIT : It worked with --size = x y 
At least I dont have any syntax error, but when I type 1280 720, process got terminated before running first iteration.
Does pixray has a resolution limit ?

**Comment by dribnet** [comment]
Sorry for this frustration - yes `--size W H` is the intended command line version though we could consider supporting other formats as well such as `W,H` or `WxH`. there is no resolution limit though you might have run out of CUDA memory. To check this you can try the fft drawer (`--drawer fft`) which is generally more memory efficient.
