### ISSUE TITLE
How does PixelDraw work?

### ISSUE THREAD

**Issue by jinyeom** [pixray/pixray#45]
Hello, and thank you so much for this awesome tool!

As I was reading through the code, I somewhat understood that pixeldraw uses diffvg for rendering, but am struggling to grasp exactly how diffvg generates a "pixel art" style image. @dribnet could you possibly help me understand the mechanism please? Thank you so much!

**Comment by samedii** [comment]
It uses this library https://github.com/BachiLi/diffvg to draw a grid of filled in squares that are the "pixels". Pixray then optimizes the colors of the squares

An alternative implementation is to draw a small image e.g. 32x32 and then do nearest neighbour upsampling to 256x256 but diffvg also allows a lot of other possibilities like hexagonal "pixels"

**Comment by dribnet** [comment]
Yes - it is similar in spirit to ClipDraw, [which you can read about here](https://kvfrans.com/clipdraw-exploring-text-to-drawing-synthesis/). The main change is that instead of allowing the curves to move around, the pixel version draws squares and only allow them to update their color.
