### ISSUE TITLE
ImportError: cannot import name 'SimpleTokenizer' from 'tokenizer'

### ISSUE THREAD

**Issue by DillFrescott** [pixray/pixray#49]
I keep getting this error...

ImportError: cannot import name 'SimpleTokenizer' from 'tokenizer' (C:\Users\micro\anaconda3\envs\pixel\lib\site-packages\tokenizer\__init__.py)

**Comment by samedii** [comment]
Did you forget to `git clone --recursive`?

**Comment by Julianiolo** [comment]
I had that problem when I was trying out a colab notebook, but I'm not sure what fixed it. Either it was me fixing the dependency download or something. I also had some issues with the notebook kinda glitching maybe that was the problem.

**Comment by samedii** [comment]
I think you are unable to import this file: https://github.com/facebookresearch/SLIP/blob/c6faf5d03cbfa7d529d210779f859cd3dddec09a/tokenizer.py

Should be because you failed to clone. I recommend looking in discord. People have asked about this before.

**Comment by DillFrescott** [comment]
Thank you guys! I appreciate the help!

**Comment by zeke** [comment]
I hit this error today and `git clone --recursive` did the trick.

**Comment by huyremy** [comment]
and...how to fix? I try and get the same error, **git clone --recursive** not help anything.
