### ISSUE TITLE
Pixray not loading on chromebook with Lightspeed

### ISSUE THREAD

**Issue by Erisfiregamer1** [pixray/pixray#5]
Hey! I like Pixray, it can make some cool art. (better then me D:)
However, on my Chromebook at school, it cannot load the Input or Output areas without a proxy. I'm using the Lightspeed blocker if that helps.

**Comment by Erisfiregamer1** [comment]
Found the issue. Lightspeed blocks replicate.com as a proxy (what), so it won't work. Big sad.

**Comment by dribnet** [comment]
Hey @bfirsh / @zeke are you aware of this replicate proxy issue on chromebooks? 

@Erisfiregamer1 - this might be an issue with our embeds (which we might be phasing out). you can try using the [tex2pixel](https://replicate.com/dribnet/pixray-text2pixel) or [text2image](https://replicate.com/dribnet/pixray-text2image) directly on the replicate site which might work better for you.

**Comment by Erisfiregamer1** [comment]
Problem with that: lightspeed blocks replicate as security.proxy
can't do that.

**Comment by bfirsh** [comment]
Interesting. Sounds like it might be your school's policy to block Replicate, or something?

**Comment by Erisfiregamer1** [comment]
Yep. That's my whole issue here, I guess.

**Comment by dribnet** [comment]
Ah - sorry I didn't realise it was a school proxy filter. Perhaps it is because of the new-ish domain name - I've seen policies where newly registered domains and blocked to prevent content from domain hopping.

**Comment by Erisfiregamer1** [comment]
> Ah - sorry I didn't realise it was a school proxy filter. Perhaps it is because of the new-ish domain name - I've seen policies where newly registered domains and blocked to prevent content from domain hopping.

They blocked it manually as security.proxy and a request to have it changed was auto-denied. They have really bad systems in place...
