### ISSUE TITLE
Triggering language in documentation

### ISSUE THREAD

**Issue by catarak** [pixray/pixray#56]
Big fan of this project! I was looking at the documentation for the [primary settings](https://dazhizhong.gitbook.io/pixray-docs/docs/primary-settings) and I noticed that one of the prompts is `prompts="suicide at the brooklyn bridge | film noir"`. Would it be possible to change this prompt to something that doesn't need a trigger warning/content warning?

I would make a pull request but I couldn't find the repo for the documentation, would it be possible to direct me there? Thank you!

**Comment by dribnet** [comment]
Thanks Cassie for the feedback - I have made this change in the repo [here](https://github.com/pixray/pixray-docs/commit/00eed902922cfb1dbee4dc80976d58f21cf9f608) and this should show up as soon as @DazhiZhong refreshes the website.

**Comment by catarak** [comment]
yay amazing, thank you so much!
