### ISSUE TITLE
No module named 'pydiffvg'

### ISSUE THREAD

**Issue by DillFrescott** [pixray/pixray#65]
The solution says to run `pip install pydiffpriv` but it cant be found anywhere even on pypl. :/

**Comment by sgallag-insta** [comment]
Not sure which solution you are referring to here, but it sounds like you don't have `diffvg` set up. You should be able to get it set up by running the following:

```
cd pixray
git clone https://github.com/pixray/diffvg
cd diffvg 
git submodule update --init --recursive 
python setup.py install 
```

[Installation docs](https://dazhizhong.gitbook.io/pixray-docs/quickstart/installation)

**Comment by dillfrescott** [comment]
Gotcha. Thank you!
