### ISSUE TITLE
Royalties

### ISSUE THREAD

**Issue by tudorelu** [pixray/pixray#7]
Hi,

This library is awesome. So is the work you're doing with generative AI artworks. Thank you.

I am playing with the idea of using pixray for an NFT project / collection. 
What is your view on this and if you're OK with it, what works for you in terms of royalties? 
We can converse via email as well, mine is tudor [dot] barbu7 [at] gmail com.

**Comment by dribnet** [comment]
This sounds great - pixray supports artists for all types of derivative uses.  For NFT projects pixray requests 5% of initial sales and 0.5% of resales to find further development and support server costs in making the online tools available for free. There are wallet addresses for various blockchains in the `USE` file in the repo; it is preferred that payments be done contractually and on-chain but if your platform does not support that then retroactive payments can be done by transfers.

Please feel free to reopen this issue if you have any further questions, or check out our #royalties channel [on our discord server](https://discord.gg/x2g9TWrNKe) where many of these discussions happen.
