### ISSUE TITLE
CMake error trying to install diffvg

### ISSUE THREAD

**Issue by palexpereira** [pixray/pixray#8]
Hello,
I apologize for the noobish question but I ran into problems trying to run with docker so I  created a python environment and installed the libraries from requirements.txt.

But after running `python pixray.py --drawer=pixel --prompt=sunrise --output myfile.png` I got the following error:

`--> Not running with pydiffvg drawer support  No module named 'pydiffvg'`

So, from where I placed the pixray files I ran this, according to requirements.txt, creating a diffvg folder inside the pixray folder:

`git clone https://github.com/pixray/diffvg && cd diffvg && git submodule update --init --recursive && CMAKE_PREFIX_PATH=$(pyenv prefix) DIFFVG_CUDA=1 python setup.py install`

But got the following error, after its done creating the diffvg files:

`FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
`
and then another

`RuntimeError: CMake must be installed to build the following extensions: diffvg`

After running `pip install cmake==3.21.3` I confirm I already have it installed, so I don't understand why it's not letting me install this diffvg module.

Is there something I'm missing here? Thanks!

My system:
Pop OS
RTX 3090

Python=3.7

**Comment by mnicstruwig** [comment]
Are you sure the python environment was active while running the build?

**Comment by palexpereira** [comment]
> Are you sure the python environment was active while running the build? Do you deactivate / reactivate your environment before running the build command?
> 
> (Otherwise your fresh install of `cmake` might not be on your `PATH`)

Thank you for the reply.
I ended up just using docker instead, I was simply missing the cuda drivers.

I had the virtual environment activated the whole time. Sorry, I don't understand what that means. I also had cmake installed in the base environment.
