### ISSUE TITLE
Models missing from server

### ISSUE THREAD

**Issue by ScanderDevMode** [pixray/pixray#82]
Hi,
I am trying to run pixray to generate anything really. After 3 days of battle, it has finally compiled with diffvg and a the current supported torch version.
Problem is, now its trying to download the models from these links ->
http://mirror.io.community/blob/vqgan/vqgan_imagenet_f16_1024.yaml
http://mirror.io.community/blob/vqgan/vqgan_imagenet_f16_16384.yaml

And they are not there.

Initially I thought maybe its the issue with wget at windows, but that's not the case as I have checked for that and wget is working.

I tried downloading the files using the links as well, but with no luck.

Here's the error I am getting ---------------------------

(Hoxrux) PS D:\work\Codes\python\Hoxrux\pixray> python pixray.py --prompt="baby waking up" --outdir ../TestOut/03
Running with 30x1 = 30 cuts
Using seed: 283430756243400
Downloading models/vqgan_imagenet_f16_16384.yaml from https://heibox.uni-heidelberg.de/d/a7530b09fed84f80a887/files/?p=%2Fconfigs%2Fmodel.yaml&dl=1, please wait
Traceback (most recent call last):
  File "pixray.py", line 2135, in <module>
    main()
  File "pixray.py", line 2129, in main
    do_init(settings)
  File "pixray.py", line 613, in do_init
    drawer.load_model(args, device)
  File "D:\work\Codes\python\Hoxrux\pixray\vqgan.py", line 111, in load_model
    wget_file(vqgan_config_table[self.vqgan_model], config_path)
  File "D:\work\Codes\python\Hoxrux\pixray\util.py", line 266, in wget_file
    output = subprocess.check_output(['wget', '-O', out, url])
  File "C:\Users\amitk\.conda\envs\Hoxrux\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\Users\amitk\.conda\envs\Hoxrux\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\amitk\.conda\envs\Hoxrux\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\amitk\.conda\envs\Hoxrux\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Thanks in advance for any help possible. Cheers!!! :)

**Comment by dribnet** [comment]
Sorry about that. I've manually added these files to the previous release [here](https://github.com/pixray/pixray/releases/tag/v1.7.1). Can you try downloading the files from there and putting them into your models subdirectory? If that works for you I can update the defaults in the code.

**Comment by ScanderDevMode** [comment]
Hi,
Thanks for the model files, I downloaded them and it is now able to generate some stuff.

Updating the model file links in code will be very nice.

Cheers!!!. :)
