### ISSUE TITLE
No output for `line_draw`, `clipdraw` or `pixel` drawers

### ISSUE THREAD

**Issue by mnicstruwig** [pixray/pixray#9]
Hi there!

There seems to be no output, intermediate or otherwise, when using the `line_draw`, `clipdraw` or `pixel` drawers. 
I'm using the `pixray minimal` Colab notebook.

Here's the generation code I'm using:

```python
import sys
sys.path.append("pixray")
# Simple setup
import pixray

prompts = "a house that is on fire"
drawer = "clipdraw"
quality = "draft"
aspect = "portrait"

# these are good settings for pixeldraw
pixray.reset_settings()
pixray.add_settings(prompts=prompts)
pixray.add_settings(quality=quality)
pixray.add_settings(drawer=drawer)
pixray.add_settings(aspect=aspect)
pixray.add_settings(display_clear=False)
settings = pixray.apply_settings()
pixray.do_init(settings)
pixray.do_run(settings)
```

All of the intermediate and final outputs are simply a blank white image (in the case if `line_draw` and `clipdraw`) or a blank black image (in the case of `pixel`) .

The `vqgan` drawer works fine, though.

**Comment by dribnet** [comment]
I believe all these issues have been resolved with the new [simple pixray notebook](https://colab.research.google.com/github/pixray/pixray_notebooks/blob/master/pixray_simple.ipynb) which is part of the maintained set of [pixray notebooks](https://github.com/pixray/pixray_notebooks). But if this is not the case feel free to reopen.a

**Comment by sortai** [comment]
I'm having the same problem, even in the default notebooks... No matter what I do, pixel renders black and line_draw and clipdraw render white. Everything briefly went back to working a few days ago, but now it stopped again. vqgan, vdiff and fft still always work.
