### ISSUE TITLE
Blacksky

### ISSUE THREAD

**Issue by NoraArt** [pixray/pixray#99]
360-degree panoramic view, 2:1 ratio, game style, dark dreamscape, night sky, twinkling stars, serene ocean, soft lighting, shadowy background, surreal and mysterious atmosphere, fantastical island, fairytale characters, glowing particles, dreamy tones, hulusi, bicycle, desktop computer, diary, eerie and twisted elements, sinister ambiance, nightmare terror

**Comment by dribnet** [comment]
![output](https://github.com/pixray/pixray/assets/945979/3ce37e3d-6d9c-49fa-b4d0-3e12fa875a11)
